DROP TABLE IF EXISTS TALK;
DROP TABLE IF EXISTS EVENT_ATTENDANCE;
DROP TABLE IF EXISTS ATTENDEE;
DROP TABLE IF EXISTS PROFESSION;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS VENUE;


CREATE TABLE IF NOT EXISTS PROFESSION(
    PROFESSION_ID INT NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(120) NOT NULL,
    CONSTRAINT PROFESSION_PK PRIMARY KEY(PROFESSION_ID),
    CONSTRAINT PROFESSION_DESC_UK UNIQUE KEY(DESCRIPTION)
    );


CREATE TABLE IF NOT EXISTS ATTENDEE(
    ATTENDEE_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(120) NOT NULL,
    LAST_NAME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    PROFESSION_ID INT NOT NULL,
    CONSTRAINT PERSON_PK PRIMARY KEY(ATTENDEE_ID),
    CONSTRAINT PERSON_EMAIL_UK UNIQUE KEY(EMAIL),
    CONSTRAINT PERSON_PROFESSION_FK FOREIGN KEY(PROFESSION_ID)
    REFERENCES PROFESSION(PROFESSION_ID)
    );


CREATE TABLE IF NOT EXISTS VENUE(
    VENUE_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(120) NOT NULL,
    SHORT_NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(300) NOT NULL,
    CITY VARCHAR(120) NOT NULL,
    STATE VARCHAR(120) NOT NULL,
    LOCATION POINT NOT NULL,
    CONSTRAINT VENUE_PK PRIMARY KEY(VENUE_ID),
    CONSTRAINT VENUE_NAME_UK UNIQUE KEY(NAME)
    );


CREATE TABLE IF NOT EXISTS EVENT(
    EVENT_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(120) NOT NULL,
    TAGS JSON,
    SCHEDULED_DATE DATE NOT NULL,
    START_ON TIME NOT NULL,
    END_ON TIME NOT NULL,
    VENUE_ID INT NOT NULL,
    ROOM VARCHAR(50) NOT NULL,
    STATUS VARCHAR(15) NOT NULL,
    CONSTRAINT EVENT_PK PRIMARY KEY(EVENT_ID),
    CONSTRAINT EVENT_VENUE_FK FOREIGN KEY(VENUE_ID)
    REFERENCES VENUE(VENUE_ID)
    );


CREATE TABLE IF NOT EXISTS TALK(
    TALK_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(120) NOT NULL,
    DESCRIPTION VARCHAR(800) NOT NULL,
    LEVEL VARCHAR(15) NOT NULL,
    TAGS JSON,
    SPEAKER_ID INT NOT NULL,
    EVENT_ID INT NOT NULL,
    START_ON TIME NOT NULL,
    END_ON TIME NOT NULL,
    STATUS VARCHAR(15) NOT NULL,
    CONSTRAINT TALK_PK PRIMARY KEY(TALK_ID),
    CONSTRAINT TALK_ATTENDEE_FK FOREIGN KEY(SPEAKER_ID)
    REFERENCES ATTENDEE(ATTENDEE_ID),
    CONSTRAINT TALK_EVENT_FK FOREIGN KEY(EVENT_ID)
    REFERENCES EVENT(EVENT_ID)
    );


CREATE TABLE IF NOT EXISTS EVENT_ATTENDANCE(
    EVENT_ID INT NOT NULL,
    ATTENDEE_ID INT NOT NULL,
    CREATED_ON DATETIME(3) NOT NULL,
    CONSTRAINT EVENT_ATTENDANCE_PK PRIMARY KEY(EVENT_ID, ATTENDEE_ID),
    CONSTRAINT EVENT_ATTENDANCE_EVENT_FK FOREIGN KEY(EVENT_ID)
    REFERENCES EVENT(EVENT_ID),
    CONSTRAINT EVENT_ATTENDANCE_ATTENDEE_FK FOREIGN KEY(ATTENDEE_ID)
    REFERENCES ATTENDEE(ATTENDEE_ID)
    );
